### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by roaet**

### CODE REVIEW

**Comment by roaet** [comment]
Also adds resource alias (for fixing the silly trailing slash `/` issue)

**Comment by Cerberus98** [comment]
OMG 2 COMMITS

**Comment by Cerberus98** [comment]
Awesome tests

**Comment by roaet** [comment]
Not sure if serious....

**Comment by Cerberus98** [comment]
There are tests

**Comment by Cerberus98** [comment]
:+1:

**Pull request merged**
