### PR TITLE
A quick waffle to make an additional log

### PR DESCRIPTION
**Pull request by roaet**
JIRA:NCP-1800

TODO: Need to write docs and tests but otherwise seems ok.

Sample Log:

```
11ms 200 <-- req-6505a043-3c2c-4ad8-9d7b-c22b663b410a admin GET /v2.0/subnets (network_id=11111111-1111-1111-1111-111111111111) 2016-01-27 11:58:05,221
```

Usage (api-paste) [MUST BE AFTER `try_context`]:
```
[composite:neutronapi_v2_0]
use = call:neutron.auth:pipeline_factory
noauth = request_id hide_extensions try_context reqresplog extensions
         last_ip_check edit_response rolerouter
keystone = request_id authtoken keystonecontext extensions neutronapiapp_v2_0

[filter:reqresplog]
paste.filter_factory = wafflehaus.log_filters.req_resp:filter_factory
enabled = true
log_file = /home/jhammond/var/log/neutron/neutron_req_resp.log
context_key = neutron.context
```

### CODE REVIEW

**Comment by roaet** [comment]
Dropped py26 support in wafflehaus.

**Comment by roaet** [comment]
Depends on #74

**Comment by roaet** [comment]
Dropped py26 didn't work for travis. Test fails are all py26

**Comment by mpath** [comment]
I would merge if I could. :(

**Comment by mpath** [comment]
:+1:

**Pull request merged**
