### PR TITLE
Moved pagination from wafflehaus.neutron to wafflehaus

### PR DESCRIPTION
**Pull request by xroot88**
JIRA:NCP-1831

### CODE REVIEW

**Comment by quadewarren** [comment]
Can tests be written for this?

**Comment by roaet** [comment]
-2 please include tests, as well writing the documentation following the pattern of other waffles (use case, example configs, etc)

**Comment by roaet** [comment]
Can you add a test for when the resp (or app) has empty return or exception?

**Comment by roaet** [comment]
LGTM

**Comment by quadewarren** [comment]
LGTM

**Pull request merged**
