### PR TITLE
Remove dupe req-ids from simple logs

### PR DESCRIPTION
**Pull request by quadewarren**
JIRA:NCP-2010

### CODE REVIEW

**Comment by roaet** [comment]
This was here if a request id didn't exist. The request id was used for the detail log key. This is not duplicating the req-id in other places I wouldn't imagine.

**Comment by quadewarren** [comment]
No, this doesn't duplicate in other places. Should this if statement be here? It falls under "_log_simple_request" function.

**Comment by quadewarren** [comment]
I updated the code to use that generated uuid in case a req-id was missing.

**Comment by roaet** [comment]
So the reason it was there was that the simple log would need to have a request id. In situations where the reqid was missing it generated a new one. If it made a new one I wanted the reqid to say no id or something because that is important. There is duplication to ease parsing.

**Pull request closed without merging**
